### ISSUE TITLE
"EtherTrackNS" -- invalid address (arg="parent", coderType="address", value="")

### ISSUE THREAD

**Issue by sfl0r3nz05** [SunPaz/EtherTrack#2]
Hi all,

I had compile the contracts without error, however when migrate the following error appear?

~/EtherTrack/Truffle-project$ sudo truffle migrate
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.

Starting migrations...
======================
> Network name:    'development'
> Network id:      123456
> Block gas limit: 0x7a1200

1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------
   > transaction hash:    0x85595dfc88ce5439193331d5e517d75c831763fa3543c935620714c7b7a09bfc
   > Blocks: 0            Seconds: 36
   > contract address:    0x6bFcEe4E364161eee217EB2dF9967C5f7Ae1e3A4
   > block number:        10907
   > block timestamp:     1556817362
   > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
   > balance:             53694.00220492
   > gas used:            269543
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00539086 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00539086 ETH

2_deploy_basics.js
==================

   Deploying 'owned'
   -----------------
   > transaction hash:    0x595f7180b00e9cde2180d46b804e3a45299afc4f4bf3327acd62c61da4b42d38
   > Blocks: 0            Seconds: 28
   > contract address:    0xc1F65776Cf4A22b3Aa92D609EA37e042998eFCc3
   > block number:        10909
   > block timestamp:     1556817410
   > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
   > balance:             53704.00220492
   > gas used:            200906
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00401812 ETH

   Deploying 'mortal'
   ------------------
   > transaction hash:    0x7555170c36b992e815e74919dc597c2e9405c3d0cf68c3dc888cdb9e7635867d
   > Blocks: 0            Seconds: 4
   > contract address:    0x214728d177307300C8911254023C0BCF64cea224
   > block number:        10910
   > block timestamp:     1556817441
   > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
   > balance:             53714.00220492
   > gas used:            200267
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00400534 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00802346 ETH

2_deploy_core.js
================

   Replacing 'owned'
   -----------------
   > transaction hash:    0x92b2f3be6bc00c813cb335dc35c796ad5f9ea075ab560852524ad637adc66d7d
   > Blocks: 0            Seconds: 4
   > contract address:    0xA48BFdf47C645638b79a9CfB88635fabcEC2e3d4
   > block number:        10914
   > block timestamp:     1556817463
   > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
   > balance:             53729.00220492
   > gas used:            200906
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00401812 ETH

   Replacing 'mortal'
   ------------------
   > transaction hash:    0x26533a41e74782a2d227a794f9ed3ba13fcd3549d1d0890b2e294d07af963b27
   > Blocks: 0            Seconds: 4
   > contract address:    0x2d27433e38a4A3856dE73b2aB51858938329c746
   > block number:        10915
   > block timestamp:     1556817472
   > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
   > balance:             53734.00220492
   > gas used:            200267
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00400534 ETH

   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00802346 ETH

3_deploy_business.js
====================

   Deploying 'EtherTrackNS'
   ------------------------
Error:  *** Deployment Failed ***

"EtherTrackNS" -- invalid address (arg="parent", coderType="address", value="").

    at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
Truffle v5.0.14 (core: 5.0.14)
Node v12.0.0

**Comment by sfl0r3nz05** [comment]
> Hi all,
> 
> I had compile the contracts without error, however when migrate the following error appear?
> 
> ~/EtherTrack/Truffle-project$ sudo truffle migrate
> Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
> 
> # Compiling your contracts...
> > Everything is up to date, there is nothing to compile.
> 
> Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
> Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.
> 
> # Starting migrations...
> > Network name:    'development'
> > Network id:      123456
> > Block gas limit: 0x7a1200
> 
> # 1_initial_migration.js
> ## Deploying 'Migrations'
> > transaction hash:    0x85595dfc88ce5439193331d5e517d75c831763fa3543c935620714c7b7a09bfc
> > Blocks: 0            Seconds: 36
> > contract address:    0x6bFcEe4E364161eee217EB2dF9967C5f7Ae1e3A4
> > block number:        10907
> > block timestamp:     1556817362
> > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
> > balance:             53694.00220492
> > gas used:            269543
> > gas price:           20 gwei
> > value sent:          0 ETH
> > total cost:          0.00539086 ETH
> 
> > Saving migration to chain.
> > Saving artifacts
> 
> > Total cost:          0.00539086 ETH
> 
> # 2_deploy_basics.js
> ## Deploying 'owned'
> > transaction hash:    0x595f7180b00e9cde2180d46b804e3a45299afc4f4bf3327acd62c61da4b42d38
> > Blocks: 0            Seconds: 28
> > contract address:    0xc1F65776Cf4A22b3Aa92D609EA37e042998eFCc3
> > block number:        10909
> > block timestamp:     1556817410
> > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
> > balance:             53704.00220492
> > gas used:            200906
> > gas price:           20 gwei
> > value sent:          0 ETH
> > total cost:          0.00401812 ETH
> 
> ## Deploying 'mortal'
> > transaction hash:    0x7555170c36b992e815e74919dc597c2e9405c3d0cf68c3dc888cdb9e7635867d
> > Blocks: 0            Seconds: 4
> > contract address:    0x214728d177307300C8911254023C0BCF64cea224
> > block number:        10910
> > block timestamp:     1556817441
> > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
> > balance:             53714.00220492
> > gas used:            200267
> > gas price:           20 gwei
> > value sent:          0 ETH
> > total cost:          0.00400534 ETH
> 
> > Saving migration to chain.
> > Saving artifacts
> 
> > Total cost:          0.00802346 ETH
> 
> # 2_deploy_core.js
> ## Replacing 'owned'
> > transaction hash:    0x92b2f3be6bc00c813cb335dc35c796ad5f9ea075ab560852524ad637adc66d7d
> > Blocks: 0            Seconds: 4
> > contract address:    0xA48BFdf47C645638b79a9CfB88635fabcEC2e3d4
> > block number:        10914
> > block timestamp:     1556817463
> > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
> > balance:             53729.00220492
> > gas used:            200906
> > gas price:           20 gwei
> > value sent:          0 ETH
> > total cost:          0.00401812 ETH
> 
> ## Replacing 'mortal'
> > transaction hash:    0x26533a41e74782a2d227a794f9ed3ba13fcd3549d1d0890b2e294d07af963b27
> > Blocks: 0            Seconds: 4
> > contract address:    0x2d27433e38a4A3856dE73b2aB51858938329c746
> > block number:        10915
> > block timestamp:     1556817472
> > account:             0x51E37247B26E1d29eaAC8E550a6b2124F11B0061
> > balance:             53734.00220492
> > gas used:            200267
> > gas price:           20 gwei
> > value sent:          0 ETH
> > total cost:          0.00400534 ETH
> 
> > Saving migration to chain.
> > Saving artifacts
> 
> > Total cost:          0.00802346 ETH
> 
> # 3_deploy_business.js
> ## Deploying 'EtherTrackNS'
> Error: *** Deployment Failed ***
> 
> "EtherTrackNS" -- invalid address (arg="parent", coderType="address", value="").
> 
> ```
> at /usr/lib/node_modules/truffle/build/webpack:/packages/truffle-deployer/src/deployment.js:364:1
> at processTicksAndRejections (internal/process/task_queues.js:88:5)
> ```
> 
> Truffle v5.0.14 (core: 5.0.14)
> Node v12.0.0

In addition, normal transactions appear before the error due to the migration:

![image](https://user-images.githubusercontent.com/6643905/57094193-2e960a00-6d10-11e9-961b-e688e6797bbd.png)

**Comment by sfl0r3nz05** [comment]
In addition, some transactions are executed.

![image](https://user-images.githubusercontent.com/6643905/57107949-a9bbe800-6d31-11e9-8ba8-964f24fea067.png)

**Comment by sfl0r3nz05** [comment]
I have set two ETH metamask accounts from /Firebase/www/db/database.json

However, the view launched when the server node is running is locked.html.

I'll appreciate a response.

**Comment by MatthAmoros** [comment]
sfl0r3nz05,

Thanks for your interest in this project, I m a little busy right now but as soon as I have some spare time I will do my best to fix these issues.

Regards,

**Comment by MatthAmoros** [comment]
Dear sfl0r3nz05, 

I have updated the respository with a new version including following changes :

Included with last commit :

- Fixed migration script to remove redundant actions : As you could see, one of the scripts was an old copy of a previous migration script that is now deprecated. It should correct migration issue and narrow down the number of transactions requiered. Remember that this script also deploy a test case with one "NameService" and two "Warehouse", associated to the same node.
- Updated dapp.js mecanics to be compatible with new Web3 version shipped with Metamask.
I had to add explicit acces request to metamask account to be able to use its information.

Feel free to post any issue you find while testing this project,

I will be glad to help,

Regards,
